In [1]:
import tensorflow as tf
import numpy as np

/home/roman/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)


In [12]:
action_dim = 2

with tf.Session() as sess:
    state = np.array([[2., 0., 0.], [0., 2., 0.], [0., 0., 2.]])
    
    _state = tf.placeholder(shape=[None, 3], dtype=tf.float32)
    
    (bs, _) = tf.unstack(tf.to_int32(tf.shape(state)))
    action_augm = tf.range(action_dim, dtype=tf.int32)
    action_augm = tf.tile(action_augm, [bs])
    
    state_ = tf.tile(tf.expand_dims(_state, axis=1), [1, 1, action_dim])
    state_ = tf.reshape(state_, [-1, 3])
    state_ = tf.concat([state_, tf.one_hot(action_augm, action_dim, dtype=tf.float32)], axis=1)
    
    weight = tf.constant([[1., 0., 0., 1., 0.],[0., 1., 0., 1., 0.]])
    output = tf.einsum('bi,ji->bj',state_, weight)
    output_ = tf.reshape(output, [-1, 2, 2])
    output_ = tf.transpose(output_, [0, 2, 1])
    
    print(sess.run(state_, feed_dict={_state: state}))
    print(sess.run(output, feed_dict={_state: state}))
    print(sess.run(output_, feed_dict={_state: state}))

[[2. 0. 0. 1. 0.]
 [2. 0. 0. 0. 1.]
 [0. 2. 0. 1. 0.]
 [0. 2. 0. 0. 1.]
 [0. 0. 2. 1. 0.]
 [0. 0. 2. 0. 1.]]
[[3. 1.]
 [2. 0.]
 [1. 3.]
 [0. 2.]
 [1. 1.]
 [0. 0.]]
[[[3. 2.]
  [1. 0.]]

 [[1. 0.]
  [3. 2.]]

 [[1. 0.]
  [1. 0.]]]
